/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.81
 * Generated at: 2023-12-09 14:17:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Practice_002034;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class member3_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!--응용화학과 20211689 김현진\r\n");
      out.write("이 과제는 크롬에 최적화되어 있습니다.-->\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>회원가입</title>\r\n");
      out.write("        <style>\r\n");
      out.write("            table { \r\n");
      out.write("                margin: auto;\r\n");
      out.write("                border-collapse : collapse;\r\n");
      out.write("                border: 1px solid #000000;\r\n");
      out.write("                width: 30em;\r\n");
      out.write("                height: 20em;\r\n");
      out.write("            }\r\n");
      out.write("            th {\r\n");
      out.write("                text-align: center;\r\n");
      out.write("                font-weight: bold;\r\n");
      out.write("                background-color: #ECECEC;\r\n");
      out.write("            }\r\n");
      out.write("            th, td { border: 1px solid #000000; }\r\n");
      out.write("            .idpw { width: 8em; height: 1em; }\r\n");
      out.write("            input.imageAlign { vertical-align: middle; }\r\n");
      out.write("            .num { width: 50px; height: 3%; }\r\n");
      out.write("            #em { width: 25em; height: 1em; }\r\n");
      out.write("            #birth { width: 9em; height: 1em; }\r\n");
      out.write("            #hello { width: 400px; height: 70px; } /*고정 안 해도 됨*/\r\n");
      out.write("            ::placeholder { color: #000000; }\r\n");
      out.write("        </style>\r\n");
      out.write("    </head>\r\n");
      out.write("    <body>\r\n");
      out.write("        <form method=\"post\" action=\"Practice 34.jsp\">\r\n");
      out.write("            <table>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <th colspan=\"2\">\r\n");
      out.write("                        회원가입\r\n");
      out.write("                    </th>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <th>아이디</th>\r\n");
      out.write("                    <td><input class=\"id\" type=\"text\" name=\"id\">\r\n");
      out.write("                        <input type=\"image\" class=\"imageAlign\" src=\"image/check.gif\">\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <th>패스워드</th>\r\n");
      out.write("                    <td><input class=\"pw\" type=\"password\" name=\"pw\"></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <th>성별</th>\r\n");
      out.write("                    <td>\r\n");
      out.write("                        <input type=\"radio\" name=\"gender\" value=\"남\">남\r\n");
      out.write("                        <input type=\"radio\" name=\"gender\" value=\"여\" checked>여\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <th>국적</th>\r\n");
      out.write("                    <td>\r\n");
      out.write("                        <input type=\"text\" value=\"대한민국\" readonly>\r\n");
      out.write("                        <input type=\"button\" value=\"국적변경\" disabled>\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <th>휴대폰</th>\r\n");
      out.write("                    <td>\r\n");
      out.write("                        <select name=\"phone1\">\r\n");
      out.write("                            <option value=\"010\" selected>010</option>\r\n");
      out.write("                            <option value=\"011\">011</option>\r\n");
      out.write("                            <option value=\"017\">017</option>\r\n");
      out.write("                            <option value=\"070\">070</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("                        - <input class=\"num\" type=\"text\" name=\"phone2\" maxlength=\"4\">\r\n");
      out.write("                        - <input class=\"num\" type=\"text\" name=\"phone3\" maxlength=\"4\">\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <th>이메일</th>\r\n");
      out.write("                    <td><input id=\"em\" type=\"text\" name=\"email\"></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <th>생일</th>\r\n");
      out.write("                    <td>\r\n");
      out.write("                        <input id=\"birth\" type=\"text\" value=\"연도-월-일\" name=\"birth\">\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <th>관심분야</th>\r\n");
      out.write("                    <td>\r\n");
      out.write("                        <input type=checkbox name=\"hobby\" value=\"뉴스\">뉴스\r\n");
      out.write("                        <input type=checkbox name=\"hobby\" value=\"맛집\" checked>맛집\r\n");
      out.write("                        <input type=checkbox name=\"hobby\" value=\"책\">책\r\n");
      out.write("                        <input type=checkbox name=\"hobby\" value=\"영화\">영화\r\n");
      out.write("                        <input type=checkbox name=\"hobby\" value=\"여행\">여행\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <th>가입인사</th>\r\n");
      out.write("                    <td>\r\n");
      out.write("                        <textarea id=\"hello\" name=\"memo\" placeholder=\"회원들에게 간단한 가입인사를 남겨주세요\"></textarea>\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <th>증명사진</th>\r\n");
      out.write("                    <td>\r\n");
      out.write("                        <input type=\"file\" value=\"파일선택\">\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <th colspan=\"2\">\r\n");
      out.write("                        <input type=\"submit\" value=\"가입하기\">\r\n");
      out.write("                        <input type=\"reset\" value=\"다시작성\">\r\n");
      out.write("                    </th>\r\n");
      out.write("                </tr>\r\n");
      out.write("            </table>\r\n");
      out.write("        </form>\r\n");
      out.write("    </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
