/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.81
 * Generated at: 2023-12-17 08:21:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Practice_002021;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Calendar;

public final class calendar_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {


public String parseDay(int cnt, String day) {
   String color;
   if (cnt == 1)
          color = "red";
    else if (cnt == 7)
          color = "blue";
    else
       color = "black";
   
   return "<td><font color='" + color + "'>" + day + "</font></td>";
       
}

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Calendar");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!--응용화학과 20211689 김현진\r\n");
      out.write("이 과제는 크롬에 최적화되어 있습니다.-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Practice 21</title>\r\n");
      out.write("<style>\r\n");
      out.write("   .tb1 { \r\n");
      out.write("   		margin: auto;\r\n");
      out.write("   		font-weight: bold;   		\r\n");
      out.write("        width: 700px;\r\n");
      out.write("      }\r\n");
      out.write("   .tb2 {\r\n");
      out.write("         margin: auto;\r\n");
      out.write("         text-align: center;\r\n");
      out.write("         border-collapse: collapse;\r\n");
      out.write("         width: 700px;\r\n");
      out.write("         height: 270px;/**/\r\n");
      out.write("         \r\n");
      out.write("      }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write('\r');
      out.write('\n');

Calendar cal = Calendar.getInstance();

int year = cal.get(Calendar.YEAR); // 년
int month = cal.get(Calendar.MONTH) + 1; // 월
int date = cal.get(Calendar.DATE); // 일

String sYear = request.getParameter("YEAR");
if (sYear != null) {
    year = Integer.parseInt(sYear);
}
String sMonth = request.getParameter("MONTH");
if (sMonth != null) {
    month = Integer.parseInt(sMonth);
}
cal.set(year, month-1, 1);

      out.write("\r\n");
      out.write("<table class=tb1>\r\n");
      out.write("<tr>\r\n");
      out.write("<th style=text-align:left>");

out.print("<a href=\"calendar.jsp?YEAR="+(year-1));
out.println("&MONTH=" + month + "\">" + "◀ </a>");
out.println(year + "년");
out.print("<a href=\"calendar.jsp?YEAR="+(year+1));
out.println("&MONTH=" + month + "\">" + "▶ </a>");

      out.write("</th>\r\n");
      out.write("<th style=text-align:center>");

if (1 < month) {
    out.print("<a href=\"calendar.jsp?YEAR=" + year);
    out.println("&MONTH=" + (month - 1) + "\">" + "◀ </a>");
} else {
    out.print("◀ ");
}
out.println(month + "월");
if (month < 12) {
    out.print("<a href=\"calendar.jsp?YEAR=" + year);
    out.println("&MONTH=" + (month + 1) + "\">" + "▶ </a>");
} else {
    out.print(" ▶");
}

      out.write("</th>\r\n");
      out.write("<th style=text-align:right>");

Calendar today = Calendar.getInstance();
int today_year = today.get(Calendar.YEAR); // 년
int today_month = today.get(Calendar.MONTH) + 1; // 월
int today_date = today.get(Calendar.DATE); // 일
out.println(today_year + "-" + today_month + "-" + today_date);

      out.write("</th>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");

int start = cal.getMinimum(Calendar.DATE); // 현재 기준 월(月)의 시작하는 날 구하기
int end = cal.getActualMaximum(Calendar.DAY_OF_MONTH); // 현재 기준 월(月)의 마지막 날 구하기
int startDay = cal.get(Calendar.DAY_OF_WEEK);

int totalDaysInMonth = end - start + 1;
int remainingDays = totalDaysInMonth - (7 - startDay + 1);
int amountWeeks = 1;
amountWeeks += remainingDays / 7;
if (remainingDays % 7 != 0)
	amountWeeks++;

      out.write("\r\n");
      out.write("<table border='1' class=tb2>\r\n");
      out.write("   <tr>\r\n");

//out.println("<table border='1' class=tb2><tr>");
    String[] WeekDay = { "", "일", "월", "화", "수", "목", "금", "토" };
    for (int i = 1; i <= 7; i++) {
      String day = WeekDay[i];
      String color = parseDay(i, day);
      out.println(color);
   }

      out.write("\r\n");
      out.write("   </tr>\r\n");

int i = 1;
int spCount = 0;
for (int row = 0; row < amountWeeks; row++) {
   out.println("<tr>");
   for (int col = 1; col <= 7; col++) {
      if (row == 0 && col < startDay) {
         out.println("<td> &nbsp; </td>"); // 날짜 출력하기 전 빈칸 출력
      }
      else {
         if (end < i) { // 날짜 출력 끝나고 빈칸 출력
            int stop = (amountWeeks * 7) - spCount;
            for (int j = 0; j < stop; j++)
               out.println("<td> &nbsp; </td>");
            break;
         }
         String pd = i + ""; // 날짜 출력
         String color = parseDay(col, pd);
         out.println(color);
         i++;
      }
      spCount++;
   }
   out.println("</tr>");
}

      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
